### ISSUE TITLE
Two HMR module launched and create maximum call stack exceeded

### ISSUE THREAD

**Issue by AMontagu** [bimdata/javascript-api-client#5]
When using "@bimdata/bimdata-api-client": "^3.3.5"
with vue cli service: "@vue/cli-service": "^3.8.0"

This happen:

![Screenshot from 2019-06-19 15-20-58](https://user-images.githubusercontent.com/11883225/59769231-00f82680-92a6-11e9-905a-40add867aa6a.png)

**Comment by benjaminaudet** [comment]
We'll take a look about it

**Comment by Amoki** [comment]
Version 4.0.0 has been released. It does not depend on Webpack anymore and should fix this bug.

**Comment by AMontagu** [comment]
Since update:
![Screenshot from 2019-07-02 09-45-56](https://user-images.githubusercontent.com/11883225/60493990-40fbd800-9cae-11e9-9cd5-7b30f442912e.png)

**Comment by Amoki** [comment]
With version >4.0.0, you have to change from
```
import bimdata from '@bimdata/bimdata-api-client'
```
to
```
import * as bimdata from '@bimdata/bimdata-api-client'
```
