### ISSUE TITLE
Conversion error while uploading an .ifc model

### ISSUE THREAD

**Issue by Yasmine091** [bimdata/javascript-api-client#8]
Hey, well i've done a JS script to update files to my cloud, the issue here is that when i upload the file everything goes as espected, i get a response with all of its informations.
But then when i want to see this new file in the viewer, my file is marqued with a red X mark that says that there was a file conversion error, while i have a few copies of that same file working in my project, anyone had this problem before?

Informations : 

- I'm coding in JavaScript, so i use fetch to work with the API
- I send my file and its name by using a FormData so no problems there
- I get a successful response with all the informations of my file when uploaded
- I have a copy of the same file that is perfectly working and visible in the viewer

**Comment by Amoki** [comment]
Hi,
Your IFC file is invalid. I just sent you an email with the explanation.
